### ISSUE TITLE
[Enhancement] Removes Edit Advertisements option if disabled

### ISSUE THREAD

**Issue by crashzk** [Natanel-Shitrit/Server-Redirect-Plus#10]
On my servers I have the option of advertisements  disabled on all servers.
```
//=======[ ADVERTISEMENTS ]=======//
		
		// Whether the Server-Redirect Advertisements is enabled or disabled.
		// Default: "1"
		// Value Range: (0 / 1)
		"EnableAdvertisements"	"0"
``` 
Would it be possible to implement that when this feature is disabled the message to edit advertisements does not appear?

![image](https://user-images.githubusercontent.com/32937653/122705374-f6bde980-d22b-11eb-8349-5a204a7d7c16.png)

**Comment by Natanel-Shitrit** [comment]
Sounds right to me, i will hide it when it's disabled.
