### ISSUE TITLE
[Enhancement] Add option for multiple server categories

### ISSUE THREAD

**Issue by penalte** [Natanel-Shitrit/Server-Redirect-Plus#3]
As the title says i would like to allow multiple "ServerCategory"	
Example:
"Surf,FFA"

For a Surf Combat Fre For All server appear in both "Surf" and "FFA" Category.

Thanks Natanel.

**Comment by Natanel-Shitrit** [comment]
Added to dev, will be tested and pushed to master when confirmed stable 😃
0a17843

**Comment by crashzk** [comment]
Option of categories is not in the **master branch** yet right? I am using this in the case.

**Comment by Natanel-Shitrit** [comment]
Not yet, a memory leak has been identified in `dev` branch so it's not recommended for use until i fix it :)

**Comment by crashzk** [comment]
Would you like to know if the **dev** version of the branch can already be used to provide feedback for you?

I would like to confirm if I can use before upgrading and such, as I had commented on the memory leak I identified.
