### ISSUE TITLE
[Enhancement] Change servers menu sorting

### ISSUE THREAD

**Issue by Natanel-Shitrit** [Natanel-Shitrit/Server-Redirect-Plus#6]
## Options:
- By ID
- By Number of players in the server
- Alphabetically (Server name)

Feel free to suggest more options 😄

**Comment by crashzk** [comment]
Idea would be good, doubt only with the option `By Number of players in the server`.

If so, would that list be automatically updated? That is, a server that had 4 players, stayed with 12 players, it automatically changes the order of the list of servers.

It would be interesting if it were so.

**Comment by Natanel-Shitrit** [comment]
Indeed, it will change the order of the servers according to the number of players in each server.
An option to toggle between Increasing / Decreasing will also be added :)
